### ISSUE TITLE
When user "A" send text to user "B", user "B" doesn't receive that text

### ISSUE THREAD

**Issue by TextMeQA** [dzetsyn/TextMe#3]
When user "A" creates new chat and send text to "B" (no previous conversations ), user "B" receive that conversation only in notifications. Nothing shown when app is open

**Comment by TextMeQA** [comment]
Actually... User "B" receives text  ALL the time when user "A" opens the app. In notifications ONLY!

**Comment by dzetsyn** [comment]
I can't reproduce that steps. All works.
1. ![image](https://user-images.githubusercontent.com/32130043/43040851-ff3c4810-8d03-11e8-9e2a-dafd44a8e61e.png)
2. ![image](https://user-images.githubusercontent.com/32130043/43040853-12918632-8d04-11e8-932b-b9594477350e.png)
